### ISSUE TITLE
Runner package doesn't work

### ISSUE THREAD

**Issue by tomkuijsten** [kgroener/Stayin-Alive#24]
I think it's because the .target file has the wrong name. Should be the name of the package.

**Comment by tomkuijsten** [comment]
It does work now for .net 4.6.1 projects. The problem with netstandard is that the runner is a 4.6.1 project which need all libs from the NETStandard.Library package (all system dll's). The package is a dependency of the runner package, but those 4.6.1 files won't be copied to the output folder.

I suggest to close the issue.

**Comment by kgroener** [comment]
I agree
